/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Assessments {
  createdAt: Generated<Timestamp>;
  data: Json;
  id: string;
  userId: string;
}

export interface CaregiverNotes {
  body: string;
  caregiverId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  patientId: string;
}

export interface CaregiverResources {
  caregiverId: string;
  category: string;
  createdAt: Generated<Timestamp>;
  id: string;
  readTime: Generated<string>;
  summary: string;
  title: string;
}

export interface CaregiverSupportTasks {
  caregiverId: string;
  completed: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  id: string;
  patientId: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface DailyActionLogs {
  actionDate: Timestamp;
  completed: Generated<boolean>;
  goalId: string;
  id: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface DailyAssessments {
  createdAt: Generated<Timestamp>;
  data: Json;
  id: string;
  logDate: Timestamp;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Goals {
  category: string;
  completed: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  generatedGoalKey: string | null;
  id: string;
  title: string;
  userId: string;
}

export interface PatientProfiles {
  consentGiven: boolean;
  createdAt: Generated<Timestamp>;
  dateOfBirth: Timestamp;
  id: string;
  sex: string;
  survivorshipSymptoms: Json;
  treatmentHistory: Json;
  treatmentStatus: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface RecommendationProgress {
  completed: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  id: string;
  recommendationId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Recommendations {
  createdAt: Generated<Timestamp>;
  id: string;
  items: Json;
  modelVersion: string;
  userId: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  id: string;
  name: string;
  passwordHash: string;
  role: string;
}

export interface WeeklyAchievements {
  completedActions: number;
  createdAt: Generated<Timestamp>;
  id: string;
  loggedDays: number;
  score: number;
  skippedActions: Generated<number>;
  totalActions: number;
  updatedAt: Generated<Timestamp>;
  userId: string;
  weekStart: Timestamp;
}

export interface WeeklyPlanActionLogs {
  actionDate: Timestamp;
  actionKey: string;
  id: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
  weeklyPlanId: string;
}

export interface WeeklyPlans {
  createdAt: Generated<Timestamp>;
  id: string;
  items: Json;
  modelVersion: string;
  reason: string;
  source: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
  weekStart: Timestamp;
}

export interface DB {
  assessments: Assessments;
  caregiverNotes: CaregiverNotes;
  caregiverResources: CaregiverResources;
  caregiverSupportTasks: CaregiverSupportTasks;
  dailyActionLogs: DailyActionLogs;
  dailyAssessments: DailyAssessments;
  goals: Goals;
  patientProfiles: PatientProfiles;
  recommendationProgress: RecommendationProgress;
  recommendations: Recommendations;
  users: Users;
  weeklyAchievements: WeeklyAchievements;
  weeklyPlanActionLogs: WeeklyPlanActionLogs;
  weeklyPlans: WeeklyPlans;
}
